### ISSUE TITLE
Is the completed remake of G!A4S Video Maker going to be free without the watermark? And is this remake going to be free?

### ISSUE THREAD

**Issue by CoolCoderTech** [goanimateforschools/goanimateforschools.github.io#3]
Is the completed remake of G!A4S Video Maker going to be free without the watermark? And is this remake going to be free?

**Comment by josephcrosmanplays532** [comment]
I was actually going to add a account system where you have to pay. but sence that got f***ed up, that won't be happening. go i guess that this lvm is going to be free.

**Comment by josephcrosmanplays532** [comment]
I was actually going to add a account system where you have to pay. but sence that got f***ed up, that won't be happening. go i guess that this lvm is going to be free.
